### ISSUE TITLE
Duplicate seeMore event being triggered

### ISSUE THREAD

**Issue by Damil2020** [dnldsht/vue-insta-stories#9]
Hi folks!
First of all, thank you for this awesome project.
I am facing a problem when trying to use the seeMore event. Everytime I click or tap the link it the event gets triggered twice.
Could you please help me?

Thanks in advance!

**Comment by dnldsht** [comment]
Hi! Thanks for giving a try to this library, yes we are glad to help.

Does the bug also happen on the demo app that is provided? Can you show us how you get that behavior

**Comment by Damil2020** [comment]
Hi! I'm not sure if the demo has it also as I don't see any methods hooked on that event on the sample code. I'm afraid I don't have my source code published yet but I basically installed your library on a Nuxt.js powered app, put it inside a <client-only> tag to prevent SSR from pre-rendering the content and added a v-on:seeMore="viewMoreStory" to the <Stories> tag.

The viewMoreStory method is this one:
`    
viewMoreStory(story) {
      console.log('View more');
}
`
And when I check the console I always see it called twice.

I hope that helps, it would be great if you could help me fixing this as it is going to duplicate every metrics or actions I need to inject.

Thanks!!

**Comment by Damil2020** [comment]
Hi folks,
sorry for disturbing, but have you had any chance of reviewing this issue?
Thanks!

**Comment by dnldsht** [comment]
Hi! Im able to reproduce this only when I'have the developer console open with a small device screen because i get the mouse event and the touch event.

Are you able to reproduce this behavior in desktop mode or with a real smartphone because I can't.
